nome : jogo da cobra

em :
  cronograma :
      # Será atualizado a cada 5 horas.
-cron     : " 0 */5 * * * "


  workflow_dispatch :

#Regras _
empregos :
  construir :
    run-on : ubuntu-latest
    passos :

      - usa : actions/checkout@v2

   
      - usa : Platane/snk@master
        id : cobra-gif
        com :
          github_user_name : Emillycristina # Seu usuario
          gif_out_path : dist/github-contribution-grid-snake.gif
          svg_out_path : dist/github-contribution-grid-snake.svg

      - executar : git status

     
      - nome : Empurre alterações
        usa : ad-m/github-push-action@master
        com :
          github_token : ${{ secrets.GITHUB_TOKEN }}
          ramo : mestre
          força : verdade

      - usa : crazy-max/ghaction-github-pages@v2.1.3
        com :
         
          target_branch : saída
          build_dir : dist
        ambiente :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
